---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run prettier
        uses: actionsx/prettier@v3
        with:
          args: --check "**/*.js"
